name: weather_prediction

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  liquid_pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true
